minimumReleaseAgeExclude:
  - brace-expansion@5.0.9
  - '@yohawing/three-mmd-loader@0.8.3'
  - nanoid@6.0.1
patchedDependencies:
  '@yohawing/three-mmd-loader@0.8.3': patches/@yohawing__three-mmd-loader@0.8.3.patch
