minimumReleaseAgeExclude:
  - brace-expansion@5.0.8
  - '@types/react-dom@19.2.4'
  - mediabunny@1.52.2 || 1.52.3
  - vite@8.2.0
  - '@yohawing/three-mmd-loader@0.8.1'
  - nanoid@6.0.1
  - dompurify@3.4.13
  - marked@18.0.9
patchedDependencies:
  '@yohawing/three-mmd-loader@0.8.1': patches/@yohawing__three-mmd-loader@0.8.1.patch
