import type { AppDefinition, WindowState } from "./types";

export const apps: AppDefinition[] = [
  {
    id: "files",
    title: "Files",
    icon: "solar:folder-with-files-bold-duotone",
    description: "Browse local virtual files",
    defaultSize: { width: 920, height: 540 },
  },
  {
    id: "notes",
    title: "Notes",
    icon: "solar:notes-bold-duotone",
    description: "Edit a saved text document",
    defaultSize: { width: 560, height: 410 },
    multiInstance: true,
  },
  {
    id: "browser",
    title: "Browser",
    icon: "solar:global-bold-duotone",
    description: "Search and open web pages",
    defaultSize: { width: 760, height: 500 },
  },
  {
    id: "calculator",
    title: "Calculator",
    icon: "solar:calculator-bold-duotone",
    description: "Quick local calculations",
    defaultSize: { width: 340, height: 460 },
  },
  {
    id: "calendar",
    title: "Calendar",
    icon: "solar:calendar-bold-duotone",
    description: "Month view and today marker",
    defaultSize: { width: 520, height: 430 },
  },
  {
    id: "settings",
    title: "Settings",
    icon: "solar:settings-bold-duotone",
    description: "System preferences and tokens",
    defaultSize: { width: 560, height: 420 },
  },
  {
    id: "terminal",
    title: "Terminal",
    icon: "solar:code-square-bold-duotone",
    description: "Run Neko shell commands",
    defaultSize: { width: 610, height: 360 },
  },
  {
    id: "task-manager",
    title: "Task Manager",
    icon: "solar:chart-2-bold-duotone",
    description: "Inspect windows and device load",
    defaultSize: { width: 720, height: 460 },
  },
  {
    id: "about",
    title: "About NekoVirtOS",
    icon: "solar:cat-bold-duotone",
    description: "System identity and build notes",
    defaultSize: { width: 510, height: 360 },
  },
];

export const initialWindows: WindowState[] = [
  {
    id: "win-files",
    appId: "files",
    title: "Files",
    icon: "solar:folder-with-files-bold-duotone",
    x: 72,
    y: 82,
    width: 920,
    height: 540,
    z: 3,
    minimized: false,
    maximized: false,
  },
  {
    id: "win-notes",
    appId: "notes",
    title: "Notes",
    icon: "solar:notes-bold-duotone",
    x: 770,
    y: 126,
    width: 545,
    height: 410,
    z: 2,
    minimized: false,
    maximized: false,
  },
  {
    id: "win-terminal",
    appId: "terminal",
    title: "Terminal",
    icon: "solar:code-square-bold-duotone",
    x: 270,
    y: 548,
    width: 620,
    height: 330,
    z: 1,
    minimized: false,
    maximized: false,
  },
];
