import type { AppDefinition } from "./appTypes";

export const apps = [
  {
    id: "files",
    title: "Files",
    titleKey: "appFiles",
    icon: "solar:folder-with-files-bold-duotone",
    description: "Browse local virtual files",
    descriptionKey: "descFiles",
    defaultSize: { width: 920, height: 540 },
  },
  {
    id: "notes",
    title: "Notes",
    titleKey: "appNotes",
    icon: "solar:notes-bold-duotone",
    description: "Edit a saved text document",
    descriptionKey: "descNotes",
    defaultSize: { width: 560, height: 410 },
    multiInstance: true,
  },
  {
    id: "browser",
    title: "Browser",
    titleKey: "appBrowser",
    icon: "solar:global-bold-duotone",
    description: "Search and open web pages",
    descriptionKey: "descBrowser",
    defaultSize: { width: 760, height: 500 },
  },
  {
    id: "calculator",
    title: "Calculator",
    titleKey: "appCalculator",
    icon: "solar:calculator-bold-duotone",
    description: "Quick local calculations",
    descriptionKey: "descCalculator",
    defaultSize: { width: 340, height: 460 },
  },
  {
    id: "calendar",
    title: "Calendar",
    titleKey: "appCalendar",
    icon: "solar:calendar-bold-duotone",
    description: "Month view and today marker",
    descriptionKey: "descCalendar",
    defaultSize: { width: 520, height: 430 },
  },
  {
    id: "tasks",
    title: "Tasks",
    titleKey: "appTasks",
    icon: "solar:checklist-minimalistic-bold-duotone",
    description: "Track local to-dos",
    descriptionKey: "descTasks",
    defaultSize: { width: 460, height: 460 },
  },
  {
    id: "timer",
    title: "Timer",
    titleKey: "appTimer",
    icon: "solar:stopwatch-bold-duotone",
    description: "Clock and stopwatch",
    descriptionKey: "descTimer",
    defaultSize: { width: 430, height: 360 },
  },
  {
    id: "palette",
    title: "Palette",
    titleKey: "appPalette",
    icon: "solar:pallete-2-bold-duotone",
    description: "Copy useful colors",
    descriptionKey: "descPalette",
    defaultSize: { width: 520, height: 420 },
  },
  {
    id: "api-tester",
    title: "API Tester",
    titleKey: "appApiTester",
    icon: "solar:server-square-cloud-bold-duotone",
    description: "Test GET and POST requests",
    descriptionKey: "descApiTester",
    defaultSize: { width: 720, height: 520 },
  },
  {
    id: "qr-tool",
    title: "QR Tool",
    titleKey: "appQrTool",
    icon: "solar:qr-code-bold-duotone",
    description: "Generate and read QR codes",
    descriptionKey: "descQrTool",
    defaultSize: { width: 680, height: 500 },
  },
  {
    id: "recorder",
    title: "Recorder",
    titleKey: "appRecorder",
    icon: "solar:microphone-3-bold-duotone",
    description: "Record microphone audio",
    descriptionKey: "descRecorder",
    defaultSize: { width: 500, height: 390 },
  },
  {
    id: "music-player",
    title: "Music Player",
    titleKey: "appMusicPlayer",
    icon: "solar:music-note-3-bold-duotone",
    description: "Play local audio files",
    descriptionKey: "descMusicPlayer",
    defaultSize: { width: 560, height: 460 },
  },
  {
    id: "video-player",
    title: "Video Player",
    titleKey: "appVideoPlayer",
    icon: "solar:video-frame-play-horizontal-bold-duotone",
    description: "Play local video files",
    descriptionKey: "descVideoPlayer",
    defaultSize: { width: 760, height: 540 },
  },
  {
    id: "settings",
    title: "Settings",
    titleKey: "appSettings",
    icon: "solar:settings-bold-duotone",
    description: "System preferences and tokens",
    descriptionKey: "descSettings",
    defaultSize: { width: 560, height: 420 },
  },
  {
    id: "terminal",
    title: "Terminal",
    titleKey: "appTerminal",
    icon: "solar:code-square-bold-duotone",
    description: "Run Neko shell commands",
    descriptionKey: "descTerminal",
    defaultSize: { width: 610, height: 360 },
  },
  {
    id: "task-manager",
    title: "Task Manager",
    titleKey: "appTaskManager",
    icon: "solar:chart-2-bold-duotone",
    description: "Inspect windows and device load",
    descriptionKey: "descTaskManager",
    defaultSize: { width: 720, height: 460 },
  },
  {
    id: "about",
    title: "About NekoVirtOS",
    titleKey: "appAbout",
    icon: "solar:cat-bold-duotone",
    description: "System identity and build notes",
    descriptionKey: "descAbout",
    defaultSize: { width: 510, height: 360 },
  },
 ] as const satisfies readonly AppDefinition[];

export type AppId = (typeof apps)[number]["id"];
