import type { AppDefinition } from "./appTypes";

export const apps = [
  {
    id: "files",
    title: "文件",
    titleKey: "appFiles",
    icon: "solar:folder-with-files-bold-duotone",
    description: "浏览本地虚拟文件",
    descriptionKey: "descFiles",
    defaultSize: { width: 1100, height: 680 },
  },
  {
    id: "trash",
    title: "回收站",
    titleKey: "appTrash",
    icon: "solar:trash-bin-trash-bold-duotone",
    description: "查看、恢复或永久删除回收站项目",
    descriptionKey: "descTrash",
    defaultSize: { width: 760, height: 480 },
  },
  {
    id: "clipboard",
    title: "剪贴板",
    titleKey: "appClipboard",
    icon: "solar:clipboard-text-bold-duotone",
    description: "收集并复用复制过的文本片段",
    descriptionKey: "descClipboard",
    defaultSize: { width: 700, height: 440 },
  },
  {
    id: "downloads",
    title: "下载",
    titleKey: "appDownloads",
    icon: "solar:download-bold-duotone",
    description: "查看本地应用导出的文件记录",
    descriptionKey: "descDownloads",
    defaultSize: { width: 720, height: 480 },
  },
  {
    id: "sticky-board",
    title: "便签板",
    titleKey: "appStickyBoard",
    icon: "solar:documents-bold-duotone",
    description: "在本地便签板上记录快速笔记",
    descriptionKey: "descStickyBoard",
    defaultSize: { width: 720, height: 500 },
  },
  {
    id: "notes",
    title: "笔记",
    titleKey: "appNotes",
    icon: "solar:notes-bold-duotone",
    description: "编辑保存的文本文件",
    descriptionKey: "descNotes",
    defaultSize: { width: 560, height: 410 },
    multiInstance: true,
  },
  {
    id: "browser",
    title: "浏览器",
    titleKey: "appBrowser",
    icon: "solar:global-bold-duotone",
    description: "搜索和打开网页",
    descriptionKey: "descBrowser",
    defaultSize: { width: 900, height: 580 },
  },
  {
    id: "calculator",
    title: "计算器",
    titleKey: "appCalculator",
    icon: "solar:calculator-bold-duotone",
    description: "带历史与记忆键的本地计算",
    descriptionKey: "descCalculator",
    defaultSize: { width: 380, height: 560 },
  },
  {
    id: "calendar",
    title: "日历",
    titleKey: "appCalendar",
    icon: "solar:calendar-bold-duotone",
    description: "月视图与本地日程",
    descriptionKey: "descCalendar",
    defaultSize: { width: 760, height: 520 },
  },
  {
    id: "tasks",
    title: "任务",
    titleKey: "appTasks",
    icon: "solar:checklist-minimalistic-bold-duotone",
    description: "优先级、截止日期与筛选",
    descriptionKey: "descTasks",
    defaultSize: { width: 560, height: 560 },
  },
  {
    id: "timer",
    title: "计时器",
    titleKey: "appTimer",
    icon: "solar:stopwatch-bold-duotone",
    description: "倒计时、秒表与本地时钟",
    descriptionKey: "descTimer",
    defaultSize: { width: 480, height: 520 },
  },
  {
    id: "palette",
    title: "调色板",
    titleKey: "appPalette",
    icon: "solar:pallete-2-bold-duotone",
    description: "取色、对比度与自定义色板",
    descriptionKey: "descPalette",
    defaultSize: { width: 600, height: 560 },
  },
  {
    id: "api-tester",
    title: "接口测试",
    titleKey: "appApiTester",
    icon: "solar:server-square-cloud-bold-duotone",
    description: "测试 GET 和 POST 请求",
    descriptionKey: "descApiTester",
    defaultSize: { width: 720, height: 520 },
  },
  {
    id: "qr-tool",
    title: "二维码工具",
    titleKey: "appQrTool",
    icon: "solar:qr-code-bold-duotone",
    description: "生成和识别二维码",
    descriptionKey: "descQrTool",
    defaultSize: { width: 680, height: 500 },
  },
  {
    id: "recorder",
    title: "录音工具",
    titleKey: "appRecorder",
    icon: "solar:microphone-3-bold-duotone",
    description: "录制麦克风音频",
    descriptionKey: "descRecorder",
    defaultSize: { width: 500, height: 390 },
  },
  {
    id: "music-player",
    title: "音乐播放器",
    titleKey: "appMusicPlayer",
    icon: "solar:music-note-3-bold-duotone",
    description: "播放本地音频文件",
    descriptionKey: "descMusicPlayer",
    defaultSize: { width: 560, height: 460 },
  },
  {
    id: "video-player",
    title: "视频播放器",
    titleKey: "appVideoPlayer",
    icon: "solar:video-frame-play-horizontal-bold-duotone",
    description: "播放本地视频文件",
    descriptionKey: "descVideoPlayer",
    defaultSize: { width: 760, height: 540 },
  },
  {
    id: "settings",
    title: "设置",
    titleKey: "appSettings",
    icon: "solar:settings-bold-duotone",
    description: "系统偏好和数据管理",
    descriptionKey: "descSettings",
    defaultSize: { width: 820, height: 580 },
  },
  {
    id: "vr-desktop",
    title: "VR 桌面",
    titleKey: "appVrDesktop",
    icon: "boxicons:vr-headset-filled",
    description: "配置并进入沉浸式桌面",
    descriptionKey: "descVrDesktop",
    defaultSize: { width: 760, height: 640 },
  },
  {
    id: "mmd-studio",
    title: "MMD 工作室",
    titleKey: "appMmdStudio",
    icon: "solar:clapperboard-edit-bold-duotone",
    description: "本地 MMD 预览与 WebM 导出",
    descriptionKey: "descMmdStudio",
    defaultSize: { width: 1280, height: 760 },
  },
  {
    id: "mmd-vr",
    title: "MMD VR",
    titleKey: "appMmdVr",
    icon: "boxicons:vr-headset-filled",
    description: "独立的 MMD VR 导入与舞台准备",
    descriptionKey: "descMmdVr",
    defaultSize: { width: 980, height: 700 },
  },
  {
    id: "terminal",
    title: "终端",
    titleKey: "appTerminal",
    icon: "solar:code-square-bold-duotone",
    description: "运行 Neko shell 命令",
    descriptionKey: "descTerminal",
    defaultSize: { width: 900, height: 560 },
  },
  {
    id: "task-manager",
    title: "任务管理器",
    titleKey: "appTaskManager",
    icon: "solar:chart-2-bold-duotone",
    description: "检查窗口和设备负载",
    descriptionKey: "descTaskManager",
    defaultSize: { width: 960, height: 620 },
  },
  {
    id: "about",
    title: "关于 NekoVirtOS",
    titleKey: "appAbout",
    icon: "solar:cat-bold-duotone",
    description: "系统身份和设备信息",
    descriptionKey: "descAbout",
    defaultSize: { width: 510, height: 360 },
  },
 ] as const satisfies readonly AppDefinition[];

export type AppId = (typeof apps)[number]["id"];
