import { create } from "zustand";

export type Language = "zh" | "en";

const LANGUAGE_STORAGE_KEY = "neko-virt-os.language.v1";

const zh = {
  appFiles: "文件",
  appTrash: "回收站",
  appClipboard: "剪贴板",
  appDownloads: "下载",
  appStickyBoard: "便签板",
  appNotes: "笔记",
  appBrowser: "浏览器",
  appCalculator: "计算器",
  appCalendar: "日历",
  appTasks: "任务",
  appTimer: "计时器",
  appPalette: "调色板",
  appApiTester: "接口测试",
  appQrTool: "二维码工具",
  appRecorder: "录音工具",
  appMusicPlayer: "音乐播放器",
  appVideoPlayer: "视频播放器",
  appSettings: "设置",
  appTerminal: "终端",
  appTaskManager: "任务管理器",
  appAbout: "关于 NekoVirtOS",
  descFiles: "浏览本地虚拟文件",
  descTrash: "查看、恢复或永久删除回收站项目",
  descClipboard: "收集并复用复制过的文本片段",
  descDownloads: "查看本地应用导出的文件记录",
  descStickyBoard: "在本地便签板上记录快速笔记",
  descNotes: "编辑保存的文本文件",
  descBrowser: "搜索和打开网页",
  descCalculator: "快速本地计算",
  descCalendar: "月视图和今日标记",
  descTasks: "跟踪本地待办",
  descTimer: "时钟和秒表",
  descPalette: "复制常用颜色",
  descApiTester: "测试 GET 和 POST 请求",
  descQrTool: "生成和识别二维码",
  descRecorder: "录制麦克风音频",
  descMusicPlayer: "播放本地音频文件",
  descVideoPlayer: "播放本地视频文件",
  descSettings: "系统偏好和数据管理",
  descTerminal: "运行 Neko shell 命令",
  descTaskManager: "检查窗口和设备负载",
  descAbout: "系统身份和设备信息",
  bootStatus: "正在启动本地工作站...",
  launcherTitle: "Neko 启动器",
  launcherSubtitle: "工作空间",
  launcherSearchPlaceholder: "搜索应用",
  launcherAllApps: "全部应用",
  loading: "正在载入...",
  open: "打开",
  rename: "重命名",
  delete: "删除",
  newFile: "新建文件",
  restore: "恢复",
  deleteForever: "永久删除",
  emptyTrash: "清空回收站",
  home: "主页",
  recent: "最近",
  trash: "回收站",
  clipboardHistory: "剪贴板历史",
  clipboardPlaceholder: "粘贴、输入或整理一段稍后要复用的文本",
  clipboardPaste: "读取剪贴板",
  clipboardSaveSnippet: "保存片段",
  clipboardNoItems: "无剪贴板项目",
  clipboardLoaded: "剪贴板已载入",
  clipboardLoadedMessage: "当前剪贴板文本已载入编辑区。",
  clipboardCopied: "文本已复制",
  clipboardCopiedMessage: "当前文本已写入系统剪贴板。",
  clipboardSaved: "片段已存储",
  clipboardSavedMessage: "当前文本已加入本地剪贴板历史。",
  clipboardReadFailedMessage: "当前浏览器上下文无法读取系统剪贴板。",
  downloadsEmpty: "无下载项目",
  downloadsClear: "清空记录",
  downloadsReady: "可再次保存",
  downloadsSessionOnly: "仅保留历史记录，当前会话文件已不可用",
  downloadsSaveAgain: "再次保存",
  exportToDownloads: "导出结果",
  stickyBoardNew: "新建便签",
  stickyBoardPlaceholder: "写一点稍后还会用到的内容",
  stickyBoardEmpty: "无便签",
  stickyBoardClearAll: "清空便签",
  filesCount: "个本地文本文件",
  mountingFs: "正在挂载本地文件系统...",
  searchFiles: "搜索文件",
  sort: "排序",
  updatedSort: "最近更新",
  nameSort: "名称",
  sizeSort: "大小",
  details: "详情",
  preview: "预览",
  noFileDetails: "文件详情",
  settingsTheme: "颜色模式",
  settingsAccent: "强调色",
  settingsDensity: "布局密度",
  settingsWallpaper: "壁纸",
  settingsWallpaperLight: "浅色壁纸",
  settingsWallpaperDark: "深色壁纸",
  settingsWallpaperOverlay: "壁纸遮罩",
  settingsWallpaperSync: "同步浅深色壁纸",
  settingsWallpaperRandom: "随机一张",
  settingsTokens: "当前 CSS Token",
  settingsData: "数据管理",
  settingsLanguage: "语言",
  settingsHeroTitle: "安静的 Neko 工作站",
  settingsHeroDescription: "外观、语言与本地数据",
  languageChinese: "中文",
  languageEnglish: "English",
  browserSearchPlaceholder: "搜索或输入地址",
  browserSearch: "搜索",
  browserFrequent: "常用页面",
  browserBlocked: "此网站可能阻止嵌入模式",
  browserBlockedMessage: "此页面可能不允许在当前窗口中显示。",
  browserOpenExternal: "在外部浏览器打开",
  browserDuplicateTab: "复制标签页",
  browserNewTabLabel: "新建标签页",
  browserRecent: "最近访问",
  browserClearRecent: "清除最近访问",
  browserSaveBookmark: "保存书签",
  browserEditBookmark: "编辑书签标题",
  browserReopenClosedTab: "恢复关闭标签",
  browserHomeText: "搜索网页、输入地址，或在标签页间切换",
  systemInfo: "系统信息",
  edition: "版本",
  interface: "界面",
  storageMode: "存储模式",
  unavailable: "不可用",
  yes: "是",
  no: "否",
  possibly: "可能",
  processor: "处理器",
  memory: "内存",
  jsHeap: "JS 堆内存",
  platform: "平台",
  architecture: "架构",
  platformVersion: "平台版本",
  browser: "浏览器",
  mobile: "移动设备",
  language: "语言",
  timezone: "时区",
  screen: "屏幕",
  viewport: "视口",
  colorDepth: "色深",
  touchPoints: "触控点",
  network: "网络",
  storage: "存储",
  secureContext: "安全上下文",
  switchWindows: "切换窗口",
  closeNotification: "关闭通知",
  clearNotifications: "清空通知",
  openWindows: "打开的窗口",
  desktop: "桌面",
  terminalOutput: "终端输出",
  performanceSummary: "性能概览",
  runningProcesses: "运行中的进程",
  deviceDetails: "设备详情",
  applicationHistory: "应用历史",
  taskManagerProcesses: "进程",
  taskManagerPerformance: "性能",
  taskManagerHistory: "应用历史",
  taskManagerSummaryPrefix: "运行窗口 ",
  taskManagerSummaryMiddle: " 个，本地文件 ",
  taskManagerSummarySuffix: " 个，已运行 ",
  taskManagerThreads: "线程",
  taskManagerJsHeap: "JS 堆",
  taskManagerOriginStorage: "源站存储",
  taskManagerLogicalProcessors: "逻辑处理器",
  taskManagerLimit: "上限",
  taskManagerQuota: "配额",
  taskManagerDisplay: "显示器",
  taskManagerPixelRatio: "像素比",
  taskManagerName: "名称",
  taskManagerStatus: "状态",
  taskManagerFootprint: "占用",
  taskManagerActions: "操作",
  taskManagerRestore: "还原",
  taskManagerSwitch: "切换",
  taskManagerEndTask: "结束任务",
  taskManagerApplication: "应用",
  taskManagerWindows: "窗口数",
  taskManagerDefaultSize: "默认尺寸",
  taskManagerRunning: "运行中",
  taskManagerSuspended: "已挂起",
  taskManagerClosed: "已关闭",
  taskManagerBackground: "后台",
  taskManagerActive: "活动中",
  taskManagerUiUnits: "界面单位",
  taskManagerFallbackProcess: "Neko 进程",
  openLauncher: "打开启动器",
  resetWindowLayoutLabel: "重置窗口布局",
  commandPalette: "命令面板",
  commandPlaceholder: "搜索应用、窗口或文件...",
  commandNoResults: "无结果",
  commandApps: "应用",
  commandWindows: "窗口",
  commandFiles: "文件",
  commandSystem: "系统",
  minimized: "已最小化",
  running: "运行中",
  desktopSubtitle: "安静的本地工作站",
  desktopGridMode: "网格",
  desktopFreeMode: "自由",
  desktopGridModeMessage: "桌面图标会吸附到网格。",
  desktopFreeModeMessage: "桌面图标可自由排布。",
  filesDeleted: "已删除",
  filesDeletedPrefix: "已删除 ",
  filesDeletedSuffix: " 个文件。",
  renameFailed: "重命名失败",
  fileRenamed: "已重命名",
  fileRenamedPrefix: "文件已重命名为 ",
  fileRenamedSuffix: "。",
  fileDeleted: "已删除",
  movedToTrash: "已移入回收站",
  movedToTrashSuffix: " 已移到回收站。",
  restoredSuffix: " 已恢复。",
  permanentlyDeletedSuffix: " 已永久删除。",
  fileCreated: "已创建",
  fileCreatedDefaultMessage: "已创建一个新的本地文本文件。",
  createFailed: "创建失败",
  createdSuffix: " 已创建。",
  canRestoreFromTrashSuffix: " 可从回收站恢复。",
  trashEmptied: "已清空回收站",
  trashEmptiedMessage: "所有回收站文件已永久删除。",
  cacheUnavailable: "缓存不可用",
  cacheUnavailableMessage: "此浏览器不支持 Cache Storage。",
  cacheCleared: "缓存已清除",
  cacheClearedPrefix: "已移除 ",
  cacheClearedSuffix: " 个缓存桶。",
  virtualStorageReset: "存储已重置",
  virtualStorageResetMessage: "默认文件已恢复。",
  siteDataCleared: "站点数据已清除",
  siteDataClearedMessage: "正在重新加载。",
  languageChanged: "语言已更新",
  languageChangedZhMessage: "界面语言已设置为中文。",
  languageChangedEnMessage: "界面语言已设置为英文。",
  themeChanged: "外观已更新",
  themeChangedPrefix: "颜色模式已设置为 ",
  themeChangedSuffix: "。",
  accentUpdated: "强调色已更新",
  accentUpdatedPrefix: "身份强调色已切换为 ",
  accentUpdatedSuffix: "。",
  densitySwitched: "布局密度已更新",
  densitySwitchedPrefix: "布局密度已设置为 ",
  densitySwitchedSuffix: "。",
  copiedToken: "已复制",
  copiedTokenSuffix: " CSS token 已复制到剪贴板。",
  copyFailed: "复制失败",
  copyFailedMessage: "当前浏览器上下文无法访问剪贴板。",
  copy: "复制",
  confirmUnsavedNotes: "关闭此窗口？未保存的更改将丢失。",
  confirmDeletePrefix: "删除 ",
  confirmDeleteSuffix: "？此操作不可撤销。",
  confirmMoveToTrashPrefix: "将 ",
  confirmMoveToTrashSuffix: " 移到回收站？",
  confirmPermanentDeletePrefix: "永久删除 ",
  confirmPermanentDeleteSuffix: "？此操作不可撤销。",
  confirmEmptyTrashPrefix: "永久删除 ",
  confirmEmptyTrashSuffix: " 个回收站文件？",
  confirmResetFiles: "重置文件？",
  confirmClearSiteData: "清除本地数据？文件、窗口和设置将被重置。",
  wallpaperSystem: "系统渐变",
  wallpaperAlpineLake: "山湖",
  wallpaperStarField: "星野",
  wallpaperPacific: "海岸",
  wallpaperGreenMeadow: "绿野",
  wallpaperForest: "森林",
  wallpaperCabin: "湖畔小屋",
  wallpaperDesertDunes: "沙丘",
  wallpaperAuroraSky: "极光",
  wallpaperSnowPeak: "雪峰",
  wallpaperCityLights: "城市夜景",
  wallpaperSunsetCoast: "海岸日落",
  wallpaperMistyForest: "雾林",
  wallpaperGraniteLake: "岩湖",
  wallpaperGlassTowers: "玻璃楼群",
  wallpaperNeonStreet: "霓虹街景",
  wallpaperCategoryBuiltIn: "内建",
  wallpaperCategoryNature: "自然",
  wallpaperCategorySky: "天空",
  wallpaperCategoryCity: "城市",
  wallpaperSourceUnsplash: "Unsplash CDN 在线加载",
  wallpaperSourceBuiltIn: "内置离线回退",
  wallpaperFit: "壁纸适配",
  wallpaperOverlayOff: "关闭",
  wallpaperOverlaySoft: "柔和",
  wallpaperOverlayStandard: "标准",
  wallpaperFitCover: "填充裁切",
  wallpaperFitContain: "完整适应",
  wallpaperFitStretch: "拉伸铺满",
  wallpaperFitTile: "平铺",
  wallpaperChanged: "壁纸已更新",
  wallpaperChangedPrefix: "桌面壁纸已设置为 ",
  wallpaperChangedSuffix: "。",
  wallpaperLoadFailed: "壁纸加载失败",
  wallpaperLoadFailedMessage: "在线图片暂时不可用，已保留当前壁纸。",
  pinnedApplication: "固定的应用",
  restoreSize: "还原大小",
  maximize: "最大化",
  minimize: "最小化",
  close: "关闭",
  cascadeWindows: "层叠窗口",
  tileWindows: "并排显示窗口",
  resetWindows: "重置窗口",
  snapLeft: "贴靠左侧",
  snapRight: "贴靠右侧",
  bringToFront: "置于最前",
  hideFromDesktop: "从桌面隐藏",
  showHiddenApplications: "显示隐藏应用",
  moveToTrash: "移到回收站",
  createTextFile: "创建文本文件",
  createFolder: "新建文件夹",
  createFolderPrompt: "输入文件夹名称",
  folderCreated: "已创建文件夹",
  newFolderLabel: "新建文件夹",
  openFolder: "打开文件夹",
  openInFiles: "在文件中打开",
  itemMoved: "已移动",
  itemMovedSuffix: " 已移动。",
  moveFailed: "移动失败",
  moveConflictError: "目标位置已存在同名项目。",
  moveIntoSelfError: "不能把文件夹移动到自身中。",
  moveIntoDescendantError: "不能把文件夹移动到它的子文件夹中。",
  moveMissingError: "找不到要移动的项目。",
  invalidTargetPath: "目标路径无效。",
  fileNameEmptyError: "名称不能为空。",
  fileNameInvalidCharsError: "名称包含不支持的字符。",
  fileNameConflictError: "该位置已存在同名项目。",
  fileNotFoundError: "找不到该项目。",
  cannotDropHere: "不能放到这里",
  dropToHome: "拖到这里可移回根目录",
  back: "后退",
  forward: "前进",
  currentPath: "当前位置",
  goUp: "返回上级",
  itemsCount: "项",
  renameFilePrompt: "重命名文件",
  trashEmpty: "无回收站项目",
  noFilesYet: "无文件",
  noFilesMatch: "无匹配文件",
  newFileLabel: "新文件",
  fileSize: "大小",
  words: "单词数",
  characters: "字符数",
  charset: "字符集",
  updated: "更新于",
  deleted: "删除于",
  noFileSelected: "无已选文件",
  notesSaved: "已保存到本地 IndexedDB",
  notesUnsaved: "未保存",
  createFileToBegin: "新建文件",
  noLocalTextSelected: "无已选文本文件",
  createFile: "创建文件",
  save: "保存",
  edit: "编辑",
  markdownPreview: "预览",
  splitView: "分栏",
  markdownPreviewUnavailable: "Markdown 预览暂时不可用。",
  tasksPlaceholder: "添加任务",
  addTask: "添加",
  clearDone: "清除完成",
  noTasks: "无任务",
  done: "已完成",
  pending: "待处理",
  start: "开始",
  pause: "暂停",
  reset: "重置",
  stopwatch: "秒表",
  localTime: "本地时间",
  copyColor: "复制颜色",
  apiUrl: "请求地址",
  apiMethod: "方法",
  apiBody: "请求体",
  apiSend: "发送请求",
  apiSending: "请求中...",
  apiResponse: "响应",
  apiHeaders: "响应头",
  apiBodyResponse: "响应体",
  apiNoResponse: "尚未发送请求。",
  apiInvalidUrl: "URL 无效。",
  apiRequestFailed: "请求失败。浏览器可能因 CORS、混合内容或网络规则阻止了请求。",
  apiRequestTimedOut: "请求超时。",
  qrGenerateTitle: "生成二维码",
  qrReadTitle: "识别二维码",
  qrText: "二维码内容",
  qrTextPlaceholder: "输入文本、链接或任意内容",
  qrUploadImage: "上传图片识别",
  qrDecodedText: "识别结果",
  qrNoCodeFound: "未检测到二维码",
  qrGeneratorUnavailable: "二维码生成暂时不可用。",
  qrReadFailed: "图片读取失败。",
  qrCopyResult: "复制结果",
  recorderReady: "准备录音",
  recorderRecording: "正在录音",
  recorderComplete: "录音完成",
  recorderStart: "开始录音",
  recorderStop: "停止录音",
  recorderDownload: "下载录音",
  recorderUnavailable: "当前浏览器不支持录音。",
  recorderPermissionDenied: "无法访问麦克风，请检查浏览器权限。",
  recorderNoClip: "无录音",
  musicAddFiles: "添加音乐",
  musicNowPlaying: "正在播放",
  musicPlaylist: "播放列表",
  musicNoTracks: "无音频",
  musicPlay: "播放",
  musicPause: "暂停",
  musicRemoveTrack: "移除曲目",
  videoAddFiles: "添加视频",
  videoNowPlaying: "正在播放",
  videoPlaylist: "视频列表",
  videoNoFiles: "无视频",
  videoFullscreen: "全屏",
  videoRemoveFile: "移除视频",
  browserGo: "前往",
  browserOpen: "打开",
  previous: "上个月",
  next: "下个月",
  dataOriginStorage: "源站存储",
  clearCache: "清除缓存",
  virtualFiles: "虚拟文件",
  resetFiles: "重置文件",
  siteData: "站点数据",
  clearSiteData: "清除站点数据",
  virtualFilesDescription: "恢复默认文件",
  siteDataDescription: "清除文件、窗口、设置与缓存",
  colorLight: "浅色",
  colorDark: "深色",
  colorSystem: "跟随系统",
  densityCozy: "舒适",
  densityCompact: "紧凑",
} as const;

const en: Record<keyof typeof zh, string> = {
  appFiles: "Files",
  appTrash: "Trash",
  appClipboard: "Clipboard",
  appDownloads: "Downloads",
  appStickyBoard: "Sticky Board",
  appNotes: "Notes",
  appBrowser: "Browser",
  appCalculator: "Calculator",
  appCalendar: "Calendar",
  appTasks: "Tasks",
  appTimer: "Timer",
  appPalette: "Palette",
  appApiTester: "API Tester",
  appQrTool: "QR Tool",
  appRecorder: "Recorder",
  appMusicPlayer: "Music Player",
  appVideoPlayer: "Video Player",
  appSettings: "Settings",
  appTerminal: "Terminal",
  appTaskManager: "Task Manager",
  appAbout: "About NekoVirtOS",
  descFiles: "Browse local virtual files",
  descTrash: "Review, restore, or permanently delete trashed items",
  descClipboard: "Collect and reuse copied text snippets",
  descDownloads: "Review files exported by local apps",
  descStickyBoard: "Keep quick notes on a local sticky board",
  descNotes: "Edit a saved text document",
  descBrowser: "Search and open web pages",
  descCalculator: "Quick local calculations",
  descCalendar: "Month view and today marker",
  descTasks: "Track local to-dos",
  descTimer: "Clock and stopwatch",
  descPalette: "Copy useful colors",
  descApiTester: "Test GET and POST requests",
  descQrTool: "Generate and read QR codes",
  descRecorder: "Record microphone audio",
  descMusicPlayer: "Play local audio files",
  descVideoPlayer: "Play local video files",
  descSettings: "System preferences and data management",
  descTerminal: "Run Neko shell commands",
  descTaskManager: "Inspect windows and device load",
  descAbout: "System identity and device info",
  bootStatus: "Starting local workstation...",
  launcherTitle: "Neko Launcher",
  launcherSubtitle: "Workspace",
  launcherSearchPlaceholder: "Search Apps",
  launcherAllApps: "All apps",
  loading: "Loading...",
  open: "Open",
  rename: "Rename",
  delete: "Delete",
  newFile: "New file",
  restore: "Restore",
  deleteForever: "Delete forever",
  emptyTrash: "Empty Trash",
  home: "Home",
  recent: "Recent",
  trash: "Trash",
  clipboardHistory: "Clipboard history",
  clipboardPlaceholder: "Paste, type, or stage text you want to reuse later",
  clipboardPaste: "Read clipboard",
  clipboardSaveSnippet: "Save snippet",
  clipboardNoItems: "No Clipboard Items",
  clipboardLoaded: "Clipboard Ready",
  clipboardLoadedMessage: "Current clipboard text was loaded into the editor.",
  clipboardCopied: "Copied",
  clipboardCopiedMessage: "Current text was written to the system clipboard.",
  clipboardSaved: "Saved",
  clipboardSavedMessage: "Current text was added to local clipboard history.",
  clipboardReadFailedMessage: "Clipboard read access is unavailable in this browser context.",
  downloadsEmpty: "No Downloads",
  downloadsClear: "Clear history",
  downloadsReady: "Available to save again",
  downloadsSessionOnly: "History kept, but the file is no longer available in this session",
  downloadsSaveAgain: "Save again",
  exportToDownloads: "Export result",
  stickyBoardNew: "New note",
  stickyBoardPlaceholder: "Write something you want to keep nearby",
  stickyBoardEmpty: "No Notes",
  stickyBoardClearAll: "Clear notes",
  filesCount: "local text files",
  mountingFs: "Mounting local filesystem...",
  searchFiles: "Search files",
  sort: "Sort",
  updatedSort: "Recently updated",
  nameSort: "Name",
  sizeSort: "Size",
  details: "Details",
  preview: "Preview",
  noFileDetails: "File Details",
  settingsTheme: "Color Mode",
  settingsAccent: "Accent Color",
  settingsDensity: "Layout Density",
  settingsWallpaper: "Wallpaper",
  settingsWallpaperLight: "Light Wallpaper",
  settingsWallpaperDark: "Dark Wallpaper",
  settingsWallpaperOverlay: "Wallpaper Overlay",
  settingsWallpaperSync: "Sync Light and Dark Wallpaper",
  settingsWallpaperRandom: "Random Wallpaper",
  settingsTokens: "Active CSS Tokens",
  settingsData: "Data Management",
  settingsLanguage: "Language",
  settingsHeroTitle: "Quiet Neko Workstation",
  settingsHeroDescription: "Appearance, language, and local data",
  languageChinese: "中文",
  languageEnglish: "English",
  browserSearchPlaceholder: "Search or Enter Address",
  browserSearch: "Search",
  browserFrequent: "Frequent pages",
  browserBlocked: "This site may block embedded mode",
  browserBlockedMessage: "This page may not allow display inside the current window.",
  browserOpenExternal: "Open in External Browser",
  browserDuplicateTab: "Duplicate Tab",
  browserNewTabLabel: "New Tab",
  browserRecent: "Recent",
  browserClearRecent: "Clear Recent",
  browserSaveBookmark: "Save Bookmark",
  browserEditBookmark: "Edit Bookmark Title",
  browserReopenClosedTab: "Reopen Closed Tab",
  browserHomeText: "Search the web, enter an address, or switch between tabs",
  systemInfo: "System information",
  edition: "Edition",
  interface: "Interface",
  storageMode: "Storage Mode",
  unavailable: "Unavailable",
  yes: "Yes",
  no: "No",
  possibly: "Possibly",
  processor: "Processor",
  memory: "Memory",
  jsHeap: "JS Heap",
  platform: "Platform",
  architecture: "Architecture",
  platformVersion: "Platform Version",
  browser: "Browser",
  mobile: "Mobile",
  language: "Language",
  timezone: "Timezone",
  screen: "Screen",
  viewport: "Viewport",
  colorDepth: "Color Depth",
  touchPoints: "Touch Points",
  network: "Network",
  storage: "Storage",
  secureContext: "Secure Context",
  switchWindows: "Switch windows",
  closeNotification: "Close notification",
  clearNotifications: "Clear notifications",
  openWindows: "Open windows",
  desktop: "Desktop",
  terminalOutput: "Terminal output",
  performanceSummary: "Performance summary",
  runningProcesses: "Running processes",
  deviceDetails: "Device details",
  applicationHistory: "Application history",
  taskManagerProcesses: "Processes",
  taskManagerPerformance: "Performance",
  taskManagerHistory: "App history",
  taskManagerSummaryPrefix: "Running windows: ",
  taskManagerSummaryMiddle: ", local files: ",
  taskManagerSummarySuffix: ", uptime: ",
  taskManagerThreads: "threads",
  taskManagerJsHeap: "JS heap",
  taskManagerOriginStorage: "Origin storage",
  taskManagerLogicalProcessors: "Logical processors",
  taskManagerLimit: "limit",
  taskManagerQuota: "quota",
  taskManagerDisplay: "Display",
  taskManagerPixelRatio: "pixel ratio",
  taskManagerName: "Name",
  taskManagerStatus: "Status",
  taskManagerFootprint: "Footprint",
  taskManagerActions: "Actions",
  taskManagerRestore: "Restore",
  taskManagerSwitch: "Switch",
  taskManagerEndTask: "End task",
  taskManagerApplication: "Application",
  taskManagerWindows: "Windows",
  taskManagerDefaultSize: "Default Size",
  taskManagerRunning: "Running",
  taskManagerSuspended: "Suspended",
  taskManagerClosed: "Closed",
  taskManagerBackground: "Background",
  taskManagerActive: "Active",
  taskManagerUiUnits: "UI units",
  taskManagerFallbackProcess: "Neko process",
  openLauncher: "Open launcher",
  resetWindowLayoutLabel: "Reset window layout",
  commandPalette: "Command Palette",
  commandPlaceholder: "Search apps, windows, or files...",
  commandNoResults: "No Results",
  commandApps: "Apps",
  commandWindows: "Windows",
  commandFiles: "Files",
  commandSystem: "System",
  minimized: "Minimized",
  running: "Running",
  desktopSubtitle: "Quiet local workstation",
  desktopGridMode: "Grid",
  desktopFreeMode: "Free",
  desktopGridModeMessage: "Desktop icons snap to the grid.",
  desktopFreeModeMessage: "Desktop icons can be placed freely.",
  filesDeleted: "Deleted",
  filesDeletedPrefix: "Successfully deleted ",
  filesDeletedSuffix: " files.",
  renameFailed: "Rename Failed",
  fileRenamed: "Renamed",
  fileRenamedPrefix: "File successfully renamed to ",
  fileRenamedSuffix: ".",
  fileDeleted: "Deleted",
  movedToTrash: "Moved to Trash",
  movedToTrashSuffix: " was moved to Trash.",
  restoredSuffix: " was restored.",
  permanentlyDeletedSuffix: " was permanently deleted.",
  fileCreated: "Created",
  fileCreatedDefaultMessage: "A new local text file was created.",
  createFailed: "Create Failed",
  createdSuffix: " created.",
  canRestoreFromTrashSuffix: " can be restored from Trash.",
  trashEmptied: "Trash Cleared",
  trashEmptiedMessage: "All trashed files were permanently deleted.",
  cacheUnavailable: "Cache Unavailable",
  cacheUnavailableMessage: "Cache Storage is not available in this browser.",
  cacheCleared: "Cache Cleared",
  cacheClearedPrefix: "Removed ",
  cacheClearedSuffix: " cache buckets.",
  virtualStorageReset: "Storage Reset",
  virtualStorageResetMessage: "Default files restored.",
  siteDataCleared: "Site Data Cleared",
  siteDataClearedMessage: "Reloading.",
  languageChanged: "Language Updated",
  languageChangedZhMessage: "Interface language set to Chinese.",
  languageChangedEnMessage: "Interface language set to English.",
  themeChanged: "Appearance Updated",
  themeChangedPrefix: "Color mode set to ",
  themeChangedSuffix: " mode.",
  accentUpdated: "Accent Updated",
  accentUpdatedPrefix: "Identity accent color changed to ",
  accentUpdatedSuffix: ".",
  densitySwitched: "Density Updated",
  densitySwitchedPrefix: "Spacing density set to ",
  densitySwitchedSuffix: " mode.",
  copiedToken: "Copied",
  copiedTokenSuffix: " CSS token copied to clipboard.",
  copyFailed: "Copy Failed",
  copyFailedMessage: "Clipboard access is unavailable in this browser context.",
  copy: "Copy",
  confirmUnsavedNotes: "Close this window? Unsaved changes will be lost.",
  confirmDeletePrefix: "Delete ",
  confirmDeleteSuffix: "? This action cannot be undone.",
  confirmMoveToTrashPrefix: "Move ",
  confirmMoveToTrashSuffix: " to Trash?",
  confirmPermanentDeletePrefix: "Permanently delete ",
  confirmPermanentDeleteSuffix: "? This action cannot be undone.",
  confirmEmptyTrashPrefix: "Permanently delete ",
  confirmEmptyTrashSuffix: " trashed files?",
  confirmResetFiles: "Reset files?",
  confirmClearSiteData: "Clear local data? Files, windows, and settings will be reset.",
  wallpaperSystem: "System gradient",
  wallpaperAlpineLake: "Alpine Lake",
  wallpaperStarField: "Star Field",
  wallpaperPacific: "Pacific Coast",
  wallpaperGreenMeadow: "Green Meadow",
  wallpaperForest: "Forest",
  wallpaperCabin: "Lakeside Cabin",
  wallpaperDesertDunes: "Desert Dunes",
  wallpaperAuroraSky: "Aurora Sky",
  wallpaperSnowPeak: "Snow Peak",
  wallpaperCityLights: "City Lights",
  wallpaperSunsetCoast: "Sunset Coast",
  wallpaperMistyForest: "Misty Forest",
  wallpaperGraniteLake: "Granite Lake",
  wallpaperGlassTowers: "Glass Towers",
  wallpaperNeonStreet: "Neon Street",
  wallpaperCategoryBuiltIn: "Built-In",
  wallpaperCategoryNature: "Nature",
  wallpaperCategorySky: "Sky",
  wallpaperCategoryCity: "City",
  wallpaperSourceUnsplash: "Loaded online from Unsplash CDN",
  wallpaperSourceBuiltIn: "Built-in offline fallback",
  wallpaperFit: "Wallpaper Fit",
  wallpaperOverlayOff: "Off",
  wallpaperOverlaySoft: "Soft",
  wallpaperOverlayStandard: "Standard",
  wallpaperFitCover: "Fill and crop",
  wallpaperFitContain: "Fit to screen",
  wallpaperFitStretch: "Stretch",
  wallpaperFitTile: "Tile",
  wallpaperChanged: "Wallpaper Updated",
  wallpaperChangedPrefix: "Desktop wallpaper set to ",
  wallpaperChangedSuffix: ".",
  wallpaperLoadFailed: "Wallpaper Load Failed",
  wallpaperLoadFailedMessage: "The online image is temporarily unavailable. Current wallpaper was kept.",
  pinnedApplication: "Pinned application",
  restoreSize: "Restore size",
  maximize: "Maximize",
  minimize: "Minimize",
  close: "Close",
  cascadeWindows: "Cascade windows",
  tileWindows: "Show windows side by side",
  resetWindows: "Reset windows",
  snapLeft: "Snap left",
  snapRight: "Snap right",
  bringToFront: "Bring to front",
  hideFromDesktop: "Hide from Desktop",
  showHiddenApplications: "Show hidden applications",
  moveToTrash: "Move to Trash",
  createTextFile: "Create text file",
  createFolder: "Create folder",
  createFolderPrompt: "Enter folder name",
  folderCreated: "Folder Created",
  newFolderLabel: "New Folder",
  openFolder: "Open folder",
  openInFiles: "Open in Files",
  itemMoved: "Moved",
  itemMovedSuffix: " moved.",
  moveFailed: "Move Failed",
  moveConflictError: "An item with the same name already exists in the destination.",
  moveIntoSelfError: "A folder cannot be moved into itself.",
  moveIntoDescendantError: "A folder cannot be moved into one of its descendants.",
  moveMissingError: "The item to move could not be found.",
  invalidTargetPath: "The target path is invalid.",
  fileNameEmptyError: "The name cannot be empty.",
  fileNameInvalidCharsError: "The name contains unsupported characters.",
  fileNameConflictError: "An item with that name already exists here.",
  fileNotFoundError: "The item could not be found.",
  cannotDropHere: "Cannot drop here",
  dropToHome: "Drop here to move back to Home",
  back: "Back",
  forward: "Forward",
  currentPath: "Current path",
  goUp: "Up",
  itemsCount: "items",
  renameFilePrompt: "Rename file",
  trashEmpty: "No Trash Items",
  noFilesYet: "No Files",
  noFilesMatch: "No Matching Files",
  newFileLabel: "New file",
  fileSize: "Size",
  words: "Words",
  characters: "Characters",
  charset: "Charset",
  updated: "Updated",
  deleted: "Deleted",
  noFileSelected: "No Selected File",
  notesSaved: "Saved locally via IndexedDB",
  notesUnsaved: "Unsaved",
  createFileToBegin: "Create File",
  noLocalTextSelected: "No Selected Text File",
  createFile: "Create file",
  save: "Save",
  edit: "Edit",
  markdownPreview: "Preview",
  splitView: "Split",
  markdownPreviewUnavailable: "Markdown preview is temporarily unavailable.",
  tasksPlaceholder: "Add task",
  addTask: "Add",
  clearDone: "Clear done",
  noTasks: "No Tasks",
  done: "Done",
  pending: "Pending",
  start: "Start",
  pause: "Pause",
  reset: "Reset",
  stopwatch: "Stopwatch",
  localTime: "Local time",
  copyColor: "Copy color",
  apiUrl: "Request URL",
  apiMethod: "Method",
  apiBody: "Request Body",
  apiSend: "Send request",
  apiSending: "Sending...",
  apiResponse: "Response",
  apiHeaders: "Response Headers",
  apiBodyResponse: "Response Body",
  apiNoResponse: "No Response",
  apiInvalidUrl: "Invalid URL.",
  apiRequestFailed: "Request failed. The browser may have blocked it with CORS, mixed-content, or network rules.",
  apiRequestTimedOut: "Request timed out.",
  qrGenerateTitle: "Generate QR Code",
  qrReadTitle: "Read QR Code",
  qrText: "QR content",
  qrTextPlaceholder: "Enter text, a link, or any content",
  qrUploadImage: "Upload image to read",
  qrDecodedText: "Decoded Result",
  qrNoCodeFound: "No QR Code Detected",
  qrGeneratorUnavailable: "QR generator is temporarily unavailable.",
  qrReadFailed: "Image read failed.",
  qrCopyResult: "Copy result",
  recorderReady: "Ready to record",
  recorderRecording: "Recording",
  recorderComplete: "Recording complete",
  recorderStart: "Start recording",
  recorderStop: "Stop recording",
  recorderDownload: "Download recording",
  recorderUnavailable: "Recording is not supported in this browser.",
  recorderPermissionDenied: "Could not access the microphone. Check browser permissions.",
  recorderNoClip: "No Recordings",
  musicAddFiles: "Add music",
  musicNowPlaying: "Now Playing",
  musicPlaylist: "Playlist",
  musicNoTracks: "No Audio Files",
  musicPlay: "Play",
  musicPause: "Pause",
  musicRemoveTrack: "Remove track",
  videoAddFiles: "Add videos",
  videoNowPlaying: "Now Playing",
  videoPlaylist: "Video List",
  videoNoFiles: "No Videos",
  videoFullscreen: "Fullscreen",
  videoRemoveFile: "Remove video",
  browserGo: "Go",
  browserOpen: "Open",
  previous: "Previous",
  next: "Next",
  dataOriginStorage: "Origin Storage",
  clearCache: "Clear cache",
  virtualFiles: "Virtual Files",
  resetFiles: "Reset files",
  siteData: "Site Data",
  clearSiteData: "Clear site data",
  virtualFilesDescription: "Restore default files",
  siteDataDescription: "Clear files, windows, settings, and cache",
  colorLight: "Light",
  colorDark: "Dark",
  colorSystem: "System",
  densityCozy: "Cozy",
  densityCompact: "Compact",
};

export type TranslationKey = keyof typeof zh;

function readLanguage(): Language {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return stored === "en" ? "en" : "zh";
  } catch {
    return "zh";
  }
}

export const useLanguageStore = create<{
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}>((set, get) => ({
  language: readLanguage(),
  setLanguage: (language) => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
    set({ language });
  },
  t: (key) => (get().language === "zh" ? zh[key] : en[key]),
}));

document.documentElement.lang = readLanguage() === "zh" ? "zh-CN" : "en";
