import { create } from "zustand";

export type Language = "zh" | "en";

const LANGUAGE_STORAGE_KEY = "neko-virt-os.language.v1";

const zh = {
  appFiles: "文件",
  appNotes: "笔记",
  appBrowser: "浏览器",
  appCalculator: "计算器",
  appCalendar: "日历",
  appTasks: "任务",
  appTimer: "计时器",
  appPalette: "调色板",
  appSettings: "设置",
  appTerminal: "终端",
  appTaskManager: "任务管理器",
  appAbout: "关于 NekoVirtOS",
  descFiles: "浏览本地虚拟文件",
  descNotes: "编辑保存的文本文件",
  descBrowser: "搜索和打开网页",
  descCalculator: "快速本地计算",
  descCalendar: "月视图和今日标记",
  descTasks: "跟踪本地待办",
  descTimer: "时钟和秒表",
  descPalette: "复制常用颜色",
  descSettings: "系统偏好和数据管理",
  descTerminal: "运行 Neko shell 命令",
  descTaskManager: "检查窗口和设备负载",
  descAbout: "系统身份和设备信息",
  bootStatus: "正在启动本地工作站...",
  launcherTitle: "Neko 启动器",
  launcherSubtitle: "打开一个安静的工作空间工具",
  open: "打开",
  rename: "重命名",
  delete: "删除",
  newFile: "新建文件",
  restore: "恢复",
  deleteForever: "永久删除",
  emptyTrash: "清空回收站",
  home: "主页",
  recent: "最近",
  trash: "回收站",
  filesCount: "个本地文本文件",
  mountingFs: "正在挂载本地文件系统...",
  searchFiles: "搜索文件",
  sort: "排序",
  updatedSort: "最近更新",
  nameSort: "名称",
  sizeSort: "大小",
  details: "详情",
  preview: "预览",
  noFileDetails: "选择文件以查看元数据和内容预览。",
  settingsTheme: "颜色模式",
  settingsAccent: "强调色",
  settingsDensity: "布局密度",
  settingsWallpaper: "壁纸",
  settingsTokens: "当前 CSS Token",
  settingsData: "数据管理",
  settingsLanguage: "语言",
  settingsHeroTitle: "安静的 Neko 工作站",
  settingsHeroDescription: "自定义主题、强调色、语言、密度和本地数据。",
  languageChinese: "中文",
  languageEnglish: "English",
  browserSearchPlaceholder: "搜索或输入网站",
  browserSearch: "搜索",
  browserFrequent: "常用页面",
  browserBlocked: "此网站可能阻止嵌入模式",
  browserExternal: "在外部标签页打开",
  browserHomeText: "搜索网页或打开 URL。浏览器会先尝试嵌入模式，站点阻止时可外部打开。",
  systemInfo: "系统信息",
  edition: "版本",
  interface: "界面",
  storageMode: "存储模式",
  unavailable: "不可用",
  yes: "是",
  no: "否",
  possibly: "可能",
  processor: "处理器",
  memory: "内存",
  jsHeap: "JS 堆内存",
  platform: "平台",
  architecture: "架构",
  platformVersion: "平台版本",
  browser: "浏览器",
  mobile: "移动设备",
  language: "语言",
  timezone: "时区",
  screen: "屏幕",
  viewport: "视口",
  colorDepth: "色深",
  touchPoints: "触控点",
  network: "网络",
  storage: "存储",
  secureContext: "安全上下文",
  switchWindows: "切换窗口",
  closeNotification: "关闭通知",
  openWindows: "打开的窗口",
  desktop: "桌面",
  terminalOutput: "终端输出",
  performanceSummary: "性能概览",
  runningProcesses: "运行中的进程",
  deviceDetails: "设备详情",
  applicationHistory: "应用历史",
  openLauncher: "打开启动器",
  resetWindowLayoutLabel: "重置窗口布局",
  commandPalette: "命令面板",
  commandPlaceholder: "搜索应用、窗口或文件...",
  commandNoResults: "没有匹配结果。",
  commandApps: "应用",
  commandWindows: "窗口",
  commandFiles: "文件",
  commandSystem: "系统",
  minimized: "已最小化",
  running: "运行中",
  desktopSubtitle: "安静的本地工作站",
  desktopGridMode: "网格",
  desktopFreeMode: "自由",
  desktopGridModeMessage: "桌面图标会吸附到网格。",
  desktopFreeModeMessage: "桌面图标可自由排布。",
  filesDeleted: "文件已删除",
  filesDeletedPrefix: "已删除 ",
  filesDeletedSuffix: " 个文件。",
  renameFailed: "重命名失败",
  fileRenamed: "文件已重命名",
  fileRenamedPrefix: "文件已重命名为 ",
  fileRenamedSuffix: "。",
  fileDeleted: "文件已删除",
  movedToTrash: "已移到回收站",
  movedToTrashSuffix: " 已移到回收站。",
  restoredSuffix: " 已恢复。",
  permanentlyDeletedSuffix: " 已永久删除。",
  fileCreated: "文件已创建",
  fileCreatedDefaultMessage: "已创建一个新的本地文本文件。",
  createFailed: "创建失败",
  createdSuffix: " 已创建。",
  canRestoreFromTrashSuffix: " 可从回收站恢复。",
  trashEmptied: "回收站已清空",
  trashEmptiedMessage: "所有回收站文件已永久删除。",
  cacheUnavailable: "缓存不可用",
  cacheUnavailableMessage: "此浏览器不支持 Cache Storage。",
  cacheCleared: "缓存已清除",
  cacheClearedPrefix: "已移除 ",
  cacheClearedSuffix: " 个缓存桶。",
  virtualStorageReset: "虚拟存储已重置",
  virtualStorageResetMessage: "默认本地文件已恢复。",
  siteDataCleared: "站点数据已清除",
  siteDataClearedMessage: "本地数据已重置，正在重新加载...",
  languageChanged: "语言已切换",
  languageChangedZhMessage: "界面语言已设置为中文。",
  languageChangedEnMessage: "界面语言已设置为英文。",
  themeChanged: "主题已切换",
  themeChangedPrefix: "颜色模式已设置为 ",
  themeChangedSuffix: "。",
  accentUpdated: "强调色已更新",
  accentUpdatedPrefix: "身份强调色已切换为 ",
  accentUpdatedSuffix: "。",
  densitySwitched: "密度已切换",
  densitySwitchedPrefix: "布局密度已设置为 ",
  densitySwitchedSuffix: "。",
  copiedToken: "Token 已复制",
  copiedTokenSuffix: " CSS token 已复制到剪贴板。",
  copyFailed: "复制失败",
  copyFailedMessage: "当前浏览器上下文无法访问剪贴板。",
  copy: "复制",
  confirmUnsavedNotes: "此笔记窗口有未保存更改，仍要关闭吗？",
  confirmDeletePrefix: "删除 ",
  confirmDeleteSuffix: "？此操作无法撤销。",
  confirmMoveToTrashPrefix: "将 ",
  confirmMoveToTrashSuffix: " 移到回收站？",
  confirmPermanentDeletePrefix: "永久删除 ",
  confirmPermanentDeleteSuffix: "？此操作无法撤销。",
  confirmEmptyTrashPrefix: "永久删除 ",
  confirmEmptyTrashSuffix: " 个回收站文件？",
  confirmResetFiles: "将虚拟文件系统重置为默认文件？",
  confirmClearSiteData: "清除 NekoVirtOS 本地数据？这会重置文件、窗口、桌面布局、主题设置和缓存。",
  wallpaperSystem: "系统渐变",
  wallpaperAlpineLake: "山湖",
  wallpaperStarField: "星野",
  wallpaperPacific: "海岸",
  wallpaperGreenMeadow: "绿野",
  wallpaperForest: "森林",
  wallpaperCabin: "湖畔小屋",
  wallpaperSourceUnsplash: "Unsplash CDN 在线加载",
  wallpaperSourceBuiltIn: "内置离线回退",
  wallpaperChanged: "壁纸已切换",
  wallpaperChangedPrefix: "桌面壁纸已设置为 ",
  wallpaperChangedSuffix: "。",
  wallpaperLoadFailed: "壁纸加载失败",
  wallpaperLoadFailedMessage: "在线图片暂时不可用，已保留当前壁纸。",
  pinnedApplication: "固定的应用",
  restoreSize: "还原大小",
  maximize: "最大化",
  minimize: "最小化",
  close: "关闭",
  cascadeWindows: "层叠窗口",
  tileWindows: "并排显示窗口",
  resetWindows: "重置窗口",
  hideFromDesktop: "从桌面隐藏",
  showHiddenApplications: "显示隐藏应用",
  moveToTrash: "移到回收站",
  createTextFile: "创建文本文件",
  renameFilePrompt: "重命名文件",
  trashEmpty: "回收站为空。",
  noFilesYet: "还没有文件。创建一个本地文本文件开始使用。",
  noFilesMatch: "没有匹配的文件。",
  newFileLabel: "新文件",
  fileSize: "大小",
  words: "单词数",
  characters: "字符数",
  charset: "字符集",
  updated: "更新于",
  deleted: "删除于",
  noFileSelected: "未选择文件",
  notesSaved: "已保存到本地 IndexedDB",
  notesUnsaved: "未保存",
  createFileToBegin: "创建文件以开始",
  noLocalTextSelected: "未选择本地文本文件。",
  createFile: "创建文件",
  save: "保存",
  edit: "编辑",
  markdownPreview: "预览",
  splitView: "分栏",
  markdownPreviewUnavailable: "Markdown 预览暂时不可用。",
  tasksPlaceholder: "添加任务",
  addTask: "添加",
  clearDone: "清除完成",
  noTasks: "没有任务。",
  done: "已完成",
  pending: "待处理",
  start: "开始",
  pause: "暂停",
  reset: "重置",
  stopwatch: "秒表",
  localTime: "本地时间",
  copyColor: "复制颜色",
  browserGo: "前往",
  browserOpen: "打开",
  previous: "上个月",
  next: "下个月",
  dataOriginStorage: "源站存储",
  clearCache: "清除缓存",
  virtualFiles: "虚拟文件",
  resetFiles: "重置文件",
  siteData: "站点数据",
  clearSiteData: "清除站点数据",
  virtualFilesDescription: "将 IndexedDB 文件存储重置为默认示例文件。",
  siteDataDescription: "清除窗口布局、桌面位置、主题设置、缓存和虚拟文件。",
  colorLight: "浅色",
  colorDark: "深色",
  colorSystem: "跟随系统",
  densityCozy: "舒适",
  densityCompact: "紧凑",
} as const;

const en: Record<keyof typeof zh, string> = {
  appFiles: "Files",
  appNotes: "Notes",
  appBrowser: "Browser",
  appCalculator: "Calculator",
  appCalendar: "Calendar",
  appTasks: "Tasks",
  appTimer: "Timer",
  appPalette: "Palette",
  appSettings: "Settings",
  appTerminal: "Terminal",
  appTaskManager: "Task Manager",
  appAbout: "About NekoVirtOS",
  descFiles: "Browse local virtual files",
  descNotes: "Edit a saved text document",
  descBrowser: "Search and open web pages",
  descCalculator: "Quick local calculations",
  descCalendar: "Month view and today marker",
  descTasks: "Track local to-dos",
  descTimer: "Clock and stopwatch",
  descPalette: "Copy useful colors",
  descSettings: "System preferences and data management",
  descTerminal: "Run Neko shell commands",
  descTaskManager: "Inspect windows and device load",
  descAbout: "System identity and device info",
  bootStatus: "Starting local workstation...",
  launcherTitle: "Neko Launcher",
  launcherSubtitle: "Open a quiet workspace tool",
  open: "Open",
  rename: "Rename",
  delete: "Delete",
  newFile: "New file",
  restore: "Restore",
  deleteForever: "Delete forever",
  emptyTrash: "Empty Trash",
  home: "Home",
  recent: "Recent",
  trash: "Trash",
  filesCount: "local text files",
  mountingFs: "Mounting local filesystem...",
  searchFiles: "Search files",
  sort: "Sort",
  updatedSort: "Recently updated",
  nameSort: "Name",
  sizeSort: "Size",
  details: "Details",
  preview: "Preview",
  noFileDetails: "Select a file to inspect metadata and preview content.",
  settingsTheme: "Color Mode",
  settingsAccent: "Accent Color",
  settingsDensity: "Layout Density",
  settingsWallpaper: "Wallpaper",
  settingsTokens: "Active CSS Tokens",
  settingsData: "Data Management",
  settingsLanguage: "Language",
  settingsHeroTitle: "Quiet Neko Workstation",
  settingsHeroDescription: "Customize theme, accent, language, density, and local data.",
  languageChinese: "中文",
  languageEnglish: "English",
  browserSearchPlaceholder: "Search or enter website",
  browserSearch: "Search",
  browserFrequent: "Frequent pages",
  browserBlocked: "This site may block embedded mode",
  browserExternal: "Open in external tab",
  browserHomeText: "Search the web or open a URL. Embedded mode is tried first, with external tab fallback when a site blocks frames.",
  systemInfo: "System information",
  edition: "Edition",
  interface: "Interface",
  storageMode: "Storage Mode",
  unavailable: "Unavailable",
  yes: "Yes",
  no: "No",
  possibly: "Possibly",
  processor: "Processor",
  memory: "Memory",
  jsHeap: "JS Heap",
  platform: "Platform",
  architecture: "Architecture",
  platformVersion: "Platform Version",
  browser: "Browser",
  mobile: "Mobile",
  language: "Language",
  timezone: "Timezone",
  screen: "Screen",
  viewport: "Viewport",
  colorDepth: "Color Depth",
  touchPoints: "Touch Points",
  network: "Network",
  storage: "Storage",
  secureContext: "Secure Context",
  switchWindows: "Switch windows",
  closeNotification: "Close notification",
  openWindows: "Open windows",
  desktop: "Desktop",
  terminalOutput: "Terminal output",
  performanceSummary: "Performance summary",
  runningProcesses: "Running processes",
  deviceDetails: "Device details",
  applicationHistory: "Application history",
  openLauncher: "Open launcher",
  resetWindowLayoutLabel: "Reset window layout",
  commandPalette: "Command Palette",
  commandPlaceholder: "Search apps, windows, or files...",
  commandNoResults: "No results found.",
  commandApps: "Apps",
  commandWindows: "Windows",
  commandFiles: "Files",
  commandSystem: "System",
  minimized: "Minimized",
  running: "Running",
  desktopSubtitle: "Quiet local workstation",
  desktopGridMode: "Grid",
  desktopFreeMode: "Free",
  desktopGridModeMessage: "Desktop icons snap to the grid.",
  desktopFreeModeMessage: "Desktop icons can be placed freely.",
  filesDeleted: "Files Deleted",
  filesDeletedPrefix: "Successfully deleted ",
  filesDeletedSuffix: " files.",
  renameFailed: "Rename Failed",
  fileRenamed: "File Renamed",
  fileRenamedPrefix: "File successfully renamed to ",
  fileRenamedSuffix: ".",
  fileDeleted: "File Deleted",
  movedToTrash: "Moved to Trash",
  movedToTrashSuffix: " was moved to Trash.",
  restoredSuffix: " was restored.",
  permanentlyDeletedSuffix: " was permanently deleted.",
  fileCreated: "File Created",
  fileCreatedDefaultMessage: "A new local text file was created.",
  createFailed: "Create Failed",
  createdSuffix: " created.",
  canRestoreFromTrashSuffix: " can be restored from Trash.",
  trashEmptied: "Trash Emptied",
  trashEmptiedMessage: "All trashed files were permanently deleted.",
  cacheUnavailable: "Cache Unavailable",
  cacheUnavailableMessage: "Cache Storage is not available in this browser.",
  cacheCleared: "Cache Cleared",
  cacheClearedPrefix: "Removed ",
  cacheClearedSuffix: " cache buckets.",
  virtualStorageReset: "Virtual Storage Reset",
  virtualStorageResetMessage: "Default local files were restored.",
  siteDataCleared: "Site Data Cleared",
  siteDataClearedMessage: "Local data was reset. Reloading...",
  languageChanged: "Language Changed",
  languageChangedZhMessage: "Interface language set to Chinese.",
  languageChangedEnMessage: "Interface language set to English.",
  themeChanged: "Theme Changed",
  themeChangedPrefix: "Color mode set to ",
  themeChangedSuffix: " mode.",
  accentUpdated: "Accent Updated",
  accentUpdatedPrefix: "Identity accent color changed to ",
  accentUpdatedSuffix: ".",
  densitySwitched: "Density Switched",
  densitySwitchedPrefix: "Spacing density set to ",
  densitySwitchedSuffix: " mode.",
  copiedToken: "Copied Token",
  copiedTokenSuffix: " CSS token copied to clipboard.",
  copyFailed: "Copy Failed",
  copyFailedMessage: "Clipboard access is unavailable in this browser context.",
  copy: "Copy",
  confirmUnsavedNotes: "This Notes window has unsaved changes. Close it anyway?",
  confirmDeletePrefix: "Delete ",
  confirmDeleteSuffix: "? This cannot be undone.",
  confirmMoveToTrashPrefix: "Move ",
  confirmMoveToTrashSuffix: " to Trash?",
  confirmPermanentDeletePrefix: "Permanently delete ",
  confirmPermanentDeleteSuffix: "? This cannot be undone.",
  confirmEmptyTrashPrefix: "Permanently delete ",
  confirmEmptyTrashSuffix: " trashed files?",
  confirmResetFiles: "Reset the virtual file system to the default files?",
  confirmClearSiteData: "Clear NekoVirtOS local data? This resets files, windows, desktop layout, theme settings, and cache storage.",
  wallpaperSystem: "System gradient",
  wallpaperAlpineLake: "Alpine Lake",
  wallpaperStarField: "Star Field",
  wallpaperPacific: "Pacific Coast",
  wallpaperGreenMeadow: "Green Meadow",
  wallpaperForest: "Forest",
  wallpaperCabin: "Lakeside Cabin",
  wallpaperSourceUnsplash: "Loaded online from Unsplash CDN",
  wallpaperSourceBuiltIn: "Built-in offline fallback",
  wallpaperChanged: "Wallpaper Changed",
  wallpaperChangedPrefix: "Desktop wallpaper set to ",
  wallpaperChangedSuffix: ".",
  wallpaperLoadFailed: "Wallpaper Load Failed",
  wallpaperLoadFailedMessage: "The online image is temporarily unavailable. Current wallpaper was kept.",
  pinnedApplication: "Pinned application",
  restoreSize: "Restore size",
  maximize: "Maximize",
  minimize: "Minimize",
  close: "Close",
  cascadeWindows: "Cascade windows",
  tileWindows: "Show windows side by side",
  resetWindows: "Reset windows",
  hideFromDesktop: "Hide from Desktop",
  showHiddenApplications: "Show hidden applications",
  moveToTrash: "Move to Trash",
  createTextFile: "Create text file",
  renameFilePrompt: "Rename file",
  trashEmpty: "Trash is empty.",
  noFilesYet: "No files yet. Create a local text file to start.",
  noFilesMatch: "No files match this search.",
  newFileLabel: "New file",
  fileSize: "Size",
  words: "Words",
  characters: "Characters",
  charset: "Charset",
  updated: "Updated",
  deleted: "Deleted",
  noFileSelected: "No file selected",
  notesSaved: "Saved locally via IndexedDB",
  notesUnsaved: "Unsaved",
  createFileToBegin: "Create a file to begin",
  noLocalTextSelected: "No local text file is selected.",
  createFile: "Create file",
  save: "Save",
  edit: "Edit",
  markdownPreview: "Preview",
  splitView: "Split",
  markdownPreviewUnavailable: "Markdown preview is temporarily unavailable.",
  tasksPlaceholder: "Add task",
  addTask: "Add",
  clearDone: "Clear done",
  noTasks: "No tasks.",
  done: "Done",
  pending: "Pending",
  start: "Start",
  pause: "Pause",
  reset: "Reset",
  stopwatch: "Stopwatch",
  localTime: "Local time",
  copyColor: "Copy color",
  browserGo: "Go",
  browserOpen: "Open",
  previous: "Previous",
  next: "Next",
  dataOriginStorage: "Origin Storage",
  clearCache: "Clear cache",
  virtualFiles: "Virtual Files",
  resetFiles: "Reset files",
  siteData: "Site Data",
  clearSiteData: "Clear site data",
  virtualFilesDescription: "Reset IndexedDB file storage to the default sample files.",
  siteDataDescription: "Clear window layout, desktop positions, theme settings, cache storage, and virtual files.",
  colorLight: "Light",
  colorDark: "Dark",
  colorSystem: "System",
  densityCozy: "Cozy",
  densityCompact: "Compact",
};

export type TranslationKey = keyof typeof zh;

function readLanguage(): Language {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return stored === "en" ? "en" : "zh";
  } catch {
    return "zh";
  }
}

export const useLanguageStore = create<{
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}>((set, get) => ({
  language: readLanguage(),
  setLanguage: (language) => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
    set({ language });
  },
  t: (key) => (get().language === "zh" ? zh[key] : en[key]),
}));

document.documentElement.lang = readLanguage() === "zh" ? "zh-CN" : "en";
